#!/bin/bash
#

# Is there any currently running instance?
# This could probably be improved to only kill
# the server, but pid tracking doesn't seem to work.
if [ -f server.pid ] ; then
  me=`whoami`
  read pid < server.pid
  for i in 1 2 3 4 5 ; do
    plist=`pgrep -u $me java | grep $pid`
    [ -z "$plist" ] && break
    echo "Killing current processes ..."
    kill -TERM $pid
    sleep 2
  done
fi
