#!/bin/sh
#

unset LC
unset LANG
export LC=en_US.UTF-8
export LANG=en_US.UTF-8

bn=`dirname $0`
if [ -z "$bn" ] ; then
  bn="."
fi
cpath="$bn"
for path in jslib jars/servlet-api-2.5.jar jars/jetty.jar jars/jetty-util.jar jars/js.jar ; do
  cpath="$cpath:$bn/$path"
done



java -classpath $cpath org.mozilla.javascript.tools.shell.Main $bn/other/rhino.js $@
